spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE