create table if not exists authors
(
    id   serial,
    name varchar not null,
    primary key (id),
    unique (name)
);

create table if not exists albums
(
    id   serial,
    year integer,
    name varchar,
    primary key (id),
    unique (name)
);

create table if not exists songs
(
    id       serial,
    year     integer,
    album_id integer,
    name     varchar not null,
    primary key (id),
    unique (name),
    foreign key (album_id) references albums
);

create table if not exists authors_songs
(
    author_id integer not null,
    song_id   integer not null,
    id        integer generated by default as identity,
    royalty   integer,
    constraint authors_songs_pk
        primary key (id),
    foreign key (author_id) references authors,
    foreign key (song_id) references songs
);

create table if not exists songs_stat
(
    song_id     integer   not null,
    date        timestamp not null,
    count_plays integer,
    primary key (date, song_id),
    foreign key (song_id) references songs
);

create table if not exists authors_albums
(
    author_id integer not null,
    album_id  integer not null,
    royalty   integer,
    id        serial,
    constraint authors_albums_pk
        primary key (id),
    foreign key (author_id) references authors,
    foreign key (album_id) references albums
);

